### PR TITLE
patch: 1.1.1 - allow-undefined-parameters_#20

### LINKED ISSUE #20: Parameter is not allowed to be undefined/null
**Describe the bug**
When logging `Data: {@Data}` and passing **error.data**, there's no guarantee that **error.data** is not undefined or null. Hence, passing a parameter which is undefined / null should be allowd

**To Reproduce**
```typescript
/*
  Just to have an object.
  We have a separate HTTPError class that extends Error
  which introduces an optional `data` property
*/
const error = {
  someProp: 'Hey'
};
logger.errorException(error, "Something. Data: {@Data}", error.data);
```

**Expected behavior**
Loglady should log Data with undefined or null in properties object

**Desktop (please complete the following information):**
 - Node.js version: [e.g. 22]
 - LogDestinations activated:
   - BetterStack
   - Console
   - Teams

### PR DESCRIPTION
**Pull request by runely**
- Allow parameter to be undefined or null and replace placeholder with 'NULL'. Improved tests to make sure output is correct
- Moved linter from **eslint** to **biome**
- Added build badges 

 Closes #20

### CODE REVIEW

File: src/lib/get-package-json.ts [hunk 1]
```diff
@@ -1,11 +1,11 @@
-import { createRequire } from 'module';
-import { join } from 'path';
+import { createRequire } from "node:module";
+import { join } from "node:path";
```
Comment (jorgtho) [inline src/lib/get-package-json.ts]: <3
